module.exports = {
  rules: {
    'no-debugger': 'error',
    'space-before-function-paren': 'off',
    'no-underscore-dangle': 'off',
    'no-param-reassign': 'off',
    'func-names': 'off',
    'no-bitwise': 'off',
    'prefer-rest-params': 'off',
    'no-trailing-spaces': 'off',
    'comma-dangle': 'off',
    'quote-props': 'off',
    'consistent-return': 'off',
    'no-plusplus': 'off',
    'prefer-spread': 'warn',
    semi: 'warn',
    indent: 'warn',
    'no-tabs': 'warn',
    'no-unused-vars': 'warn',
    quotes: 'warn',
    'no-void': 'off',
    'no-nested-ternary': 'off',
    'import/no-unresolved': 'off',
    'no-return-assign': 'warn',
    'linebreak-style': 'off',
    'prefer-destructuring': 'off',
    'no-restricted-syntax': 'warn',
    'arrow-parens': 'off',
    'import/extensions': 'off',
    'import/order': 'off',
    'import/no-extraneous-dependencies': 'off',
    'object-curly-newline': 'warn',
    'object-curly-spacing': 'warn',
    'import/no-cycle': 'off',
    'no-continue': 'off',
    'vue/no-unused-components': 'warn',
    'camelcase': 'off',
    'dot-notation': 'warn',
    'arrow-body-style': 'warn',
    'no-unused-expressions': 'warn'
  },
  globals: {
  }
};
